#!/bin/bash

srun --ntasks="${SLURM_JOB_NUM_NODES}" --container-image="${CONT}" --container-mounts="${MOUNTS}" bash -cx "\
      cd /workdir/build/bin && \
      ./checker_test && \
      ./data_reader_test && \
      ./device_map_test && \
      ./loss_test && \
      ./optimizer_test && \
      ./regularizers_test && \
      ./embedding_training_cache_test && \
      ./auc_test && \
      ./embedding_collection_test && \
      ./averageloss_test && \
      ././communication_test"
