#!/bin/bash
set -e

srun --ntasks=1 --container-image="${CONT}" --container-mounts="${MOUNTS}" bash -cx " \
    cd /workdir/sparse_operation_kit/unit_test/test_scripts/tf1 && \
    bash sok_test_unit.sh"

srun --ntasks=8 --container-image="${CONT}" --container-mounts="${MOUNTS}" bash -cx " \
    cd /workdir/sparse_operation_kit/sparse_operation_kit/experiment/test/function_test && \
    bash run_function_test.sh"
