#!/bin/bash

srun --ntasks=1 --container-image="${CONT}" bash -cx " \
    rm -rf /usr/local/lib/python\${PYTHON_VERSION}/dist-packages/merlin_sok*
    cd /workdir/sparse_operation_kit/ && \
    python setup.py sdist && \
    cd dist && \
    pip install *.tar.gz --no-build-isolation && \
    cd /workdir/sparse_operation_kit/sparse_operation_kit/test/function_test && \
    bash run_function_test.sh"

