#!/bin/bash

srun --ntasks="${SLURM_JOB_NUM_NODES}" --container-image="${CONT}" --container-mounts="${MOUNTS}" bash -cx " \
      cd ${DATASET_MOUNT}/criteo && \
      mkdir /workdir/export_predictions_criteo_1gpu/ && \
      python3 /workdir/test/pybind_test/single_node_test.py --json-file=/workdir/test/scripts/criteo_1gpu.json && \
      python3 /workdir/test/pybind_test/single_node_test.py --json-file=/workdir/test/scripts/criteo_8gpu.json && \
      cd /dataset/criteo_kaggle/criteo_multi_slots && \
      python3 /workdir/test/pybind_test/single_node_test.py --json-file=/workdir/test/scripts/criteo_multi_slots_1gpu.json && \
      python3 /workdir/test/pybind_test/single_node_test.py --json-file=/workdir/test/scripts/criteo_multi_slots_8gpu.json && \
      cd /dataset/criteo_kaggle/criteo_parquet_multi_slots && \
      python3 /workdir/test/pybind_test/single_node_test.py --json-file=/workdir/test/scripts/criteo_parquet_multi_slots_1gpu.json"