#!/bin/bash

srun --ntasks="${SLURM_JOB_NUM_NODES}" --container-image="${CONT}" --container-mounts="${MOUNTS}" bash -cx " \
    cd /dataset/criteo_kaggle/ && \
    python3 /workdir/test/embedding_collection_test/dlrm_train_ftrl.py --shard_plan round_robin"

srun --ntasks="${SLURM_JOB_NUM_NODES}" --container-image="${CONT}" --container-mounts="${MOUNTS}" bash -cx " \
    cd /dataset/criteo_kaggle/ && \
    python3 /workdir/test/embedding_collection_test/dlrm_train_ftrl.py --shard_plan uniform"

srun --ntasks="${SLURM_JOB_NUM_NODES}" --container-image="${CONT}" --container-mounts="${MOUNTS}" bash -cx " \
    cd /dataset/criteo_kaggle/ && \
    python3 /workdir/test/embedding_collection_test/dlrm_train_ftrl.py --shard_plan hybrid"

srun --ntasks="${SLURM_JOB_NUM_NODES}" --container-image="${CONT}" --container-mounts="${MOUNTS}" bash -cx " \
    cd /dataset/criteo_kaggle/ && \
    python3 /workdir/test/embedding_collection_test/dlrm_train_ftrl.py --shard_plan hybrid --grouped_allreduce"

srun --ntasks="${SLURM_JOB_NUM_NODES}" --container-image="${CONT}" --container-mounts="${MOUNTS}" \
  env NCCL_LAUNCH_MODE=GROUP bash -cx " \
    cd /dataset/criteo_kaggle/ && \
    python3 /workdir/test/embedding_collection_test/dlrm_train_ftrl.py --shard_plan round_robin --use_dynamic_hash_table"

srun --ntasks="${SLURM_JOB_NUM_NODES}" --container-image="${CONT}" --container-mounts="${MOUNTS}" \
  env NCCL_LAUNCH_MODE=GROUP bash -cx " \
    cd /dataset/criteo_kaggle/ && \
    python3 /workdir/test/embedding_collection_test/dlrm_train_ftrl.py --shard_plan uniform --use_dynamic_hash_table"

srun --ntasks="${SLURM_JOB_NUM_NODES}" --container-image="${CONT}" --container-mounts="${MOUNTS}" \
  env NCCL_LAUNCH_MODE=GROUP bash -cx " \
    cd /dataset/criteo_kaggle/ && \
    python3 /workdir/test/embedding_collection_test/dlrm_train_ftrl.py --shard_plan round_robin --use_dynamic_hash_table --optimizer ftrl "

srun --ntasks="${SLURM_JOB_NUM_NODES}" --container-image="${CONT}" --container-mounts="${MOUNTS}" \
  env NCCL_LAUNCH_MODE=GROUP bash -cx " \
    cd /dataset/criteo_kaggle/ && \
    python3 /workdir/test/embedding_collection_test/dlrm_train_ftrl.py --shard_plan round_robin --optimizer ftrl "

srun --ntasks="${SLURM_JOB_NUM_NODES}" --container-image="${CONT}" --container-mounts="${MOUNTS}" \
  env NCCL_LAUNCH_MODE=GROUP bash -cx " \
    cd /dataset/criteo_kaggle/ && \
    python3 /workdir/test/embedding_collection_test/dlrm_train_ftrl.py --shard_plan uniform --use_dynamic_hash_table --optimizer ftrl"

srun --ntasks="${SLURM_JOB_NUM_NODES}" --container-image="${CONT}" --container-mounts="${MOUNTS}" \
  env NCCL_LAUNCH_MODE=GROUP bash -cx " \
    cd /dataset/criteo_kaggle/ && \
    python3 /workdir/test/embedding_collection_test/dlrm_train_ftrl.py --shard_plan uniform --optimizer ftrl"

srun --ntasks="${SLURM_JOB_NUM_NODES}" --container-image="${CONT}" --container-mounts="${MOUNTS}" \
  env NCCL_LAUNCH_MODE=GROUP bash -cx " \
    cd /dataset/criteo_kaggle/ && \
    python3 /workdir/test/embedding_collection_test/dlrm_train_ftrl.py --shard_plan round_robin --use_mixed_precision"

srun --ntasks="${SLURM_JOB_NUM_NODES}" --container-image="${CONT}" --container-mounts="${MOUNTS}" \
  env NCCL_LAUNCH_MODE=GROUP bash -cx " \
    cd /dataset/criteo_kaggle/ && \
    python3 /workdir/test/embedding_collection_test/dlrm_train_ftrl.py --shard_plan uniform --use_mixed_precision"
