name: "hugectr_tf"
platform: "tensorflow_graphdef"
max_batch_size: 0
input [
    {
        name: "INPUT0"
        data_type: TYPE_INT64
        dims: [39]
    }
]
output [
    {
        name: "OUTPUT0",
        data_type: TYPE_FP32
        dims: [1]
    }
]

default_model_filename: "hugectr_tf.graphdef"
instance_group [
    {
        count: 8
        kind: KIND_GPU
        gpus: [ 0 ]
    }
]


