#!/bin/bash

srun --ntasks=1 --container-image="${CONT}" --container-mounts="${MOUNTS}" bash -cx " \
    chmod +x /usr/local/hugectr/bin/* && \
    cd /workdir/tools/ && \
    ln -s /workdir/tools/day_0 /workdir/test/notebook_test/day_0 && \
    bash preprocess.sh 0 wdl_data pandas 1 1 100 && \
    ln -s /workdir/tools/wdl_data /workdir/test/notebook_test/wdl_data && \
    cd /workdir/test/notebook_test && pytest notebook_hugectr.py && \
    rm -rf /workdir/test/notebook_test/wdl_data /workdir/tools/wdl_data && cd /workdir/tools"
