#!/bin/bash

srun --ntasks=1 --container-image="${CONT}" --container-mounts="${MOUNTS}" bash -cx " \
    cd /workdir/hps_torch/test/unit && \
    pytest -s && \
    cd /workdir/hps_torch/test/integration && \
    pytest test_hps_table_fusion.py -s"

# Add workaround due to the known issue of tensorflow
sleep 10
EXITCODE=`sacct -j "${SLURM_JOBID}" -n --format=exitcode | sort -r -u | head -1 | cut -f 1 -d":" | sed 's/ //g'`
echo "Job exit code: ${EXITCODE}"

if [ ${EXITCODE} -eq 6 ]&&[ ${CI_JOB_NAME}=="hps_tf" ]; then
       echo "Rerun the job, if job exit code is 6 and job name is hps_tf."
       srun --ntasks=1 --container-image="${CONT}" --container-mounts="${MOUNTS}" bash -cx " \
                cd /workdir/hps_torch/test/unit && \
                pytest -s && \
                cd /workdir/hps_torch/test/integration && \
                pytest test_hps_table_fusion.py -s"
       # Get the last job step exit code as job exit code.
       sed -i 's/sort -r -u | head -1/tail -1/g' ${JOBSCRIPTSDIR}/mlperf-ci/jobexitcode.sh
       echo "Rerun job finished!";
fi

