#!/bin/bash

srun --ntasks="${SLURM_JOB_NUM_NODES}" --container-image="${CONT}" --container-mounts="${MOUNTS}" bash -cx " \
      cd /dataset/criteo_kaggle/dcn && \
      python3 /workdir/test/pybind_test/single_node_test.py --json-file=/workdir/test/scripts/dlrm_1gpu.json && \
      python3 /workdir/test/pybind_test/single_node_test.py --json-file=/workdir/test/scripts/dlrm_8gpu.json && \
      python3 /workdir/test/pybind_test/single_node_test.py --json-file=/workdir/test/scripts/dlrm_fp16_1gpu.json && \
      python3 /workdir/test/pybind_test/single_node_test.py --json-file=/workdir/test/scripts/dlrm_fp16_8gpu.json"