#!/bin/bash
set -e

srun --ntasks="${SLURM_JOB_NUM_NODES}" bash -c "echo -n 'Clearing cache on ' && hostname && sync && sudo /sbin/sysctl vm.drop_caches=3"

srun --mpi=pmix --ntasks="${SLURM_JOB_NUM_NODES}" --ntasks-per-node=1 --container-image="${CONT}" --container-mounts="${MOUNTS}" bash -cx " \
    exec numactl --membind=1,3,5,7 python3 /workdir/samples/dlrm/dgx_a100_8x8x1120_ib_nvlink.py"

srun --mpi=pmix --ntasks="${SLURM_JOB_NUM_NODES}" --ntasks-per-node=1 --container-image="${CONT}" --container-mounts="${MOUNTS}" bash -cx " \
    python3 /workdir/test/embedding_collection_test/dgx_a100_one_hot.py --batchsize 71680 --batchsize_eval=1792000 --use_mixed_precision"
