#!/bin/bash

srun --ntasks="${SLURM_JOB_NUM_NODES}" --container-image="${CONT}" --container-mounts="${MOUNTS}" --network sharp bash -cx " \
    cd /dataset/criteo_kaggle/wdl_etc_parquet && \
    rm -rfv /tmp_dir/etc_multi_node_mem && \
    mkdir -p /tmp_dir/etc_multi_node_mem && \
    python3 /workdir/test/pybind_test/wdl_etc_mpi.py /workdir/test/scripts/wdl_etc.json /tmp_dir/etc_multi_node_mem && \
    rm -rfv /tmp_dir/etc_multi_node_mem"
