#!/bin/bash

#TODO remove ETC 
srun --ntasks="${SLURM_JOB_NUM_NODES}" --container-image="${CONT}" --container-mounts="${MOUNTS}" bash -cx " \
    cd /dataset/criteo_kaggle/wdl_etc_parquet/ && \
    rm -rfv /workdir/etc_single_node_mem && \
    mkdir -p /workdir/etc_single_node_mem && \
    python3 /workdir/test/pybind_test/wdl_etc_low_level.py /workdir/test/scripts/wdl_etc.json /workdir/etc_single_node_mem && \
    rm -rfv /workdir/etc_single_node_mem"

srun --ntasks="${SLURM_JOB_NUM_NODES}" --container-image="${CONT}" --container-mounts="${MOUNTS}" bash -cx " \
    cd /dataset/criteo_kaggle/wdl_etc_parquet/ && \
    rm -rfv /workdir/etc_single_node_mem && \
    mkdir -p /workdir/etc_single_node_mem && \
    python3 /workdir/test/pybind_test/wdl_etc.py /workdir/test/scripts/wdl_etc.json /workdir/etc_single_node_mem && \
    rm -rfv /workdir/etc_single_node_mem"
