#!/bin/bash

srun --ntasks="${SLURM_JOB_NUM_NODES}" --container-image="${CONT}" --container-mounts="${MOUNTS}" bash -cx " \
      cd ${NEW_CRITEO_MOUNT} && \
      mpirun -np 1 --allow-run-as-root python3 /workdir/test/group_fc_test/dlrm_fp16.py && \
      mpirun -np 1 --allow-run-as-root python3 /workdir/test/group_fc_test/dlrm_fp16_grad.py && \
      mpirun -np 1 --allow-run-as-root python3 /workdir/test/group_fc_test/dlrm_fp32.py"