#!/bin/bash
set -e

#TODO: add restriction of NCCL_IB_HCA for draco-oci, may need remove it for other cluster
srun --ntasks=4 --container-image="${CONT}" --container-mounts="${MOUNTS}" --network sharp bash -cx " \
    export NCCL_IB_HCA=\"=mlx5_1\" && \
    cd /dataset/criteo_kaggle/dcn_parquet && \
    python3 /workdir/test/pybind_test/multi_node_test.py --json-file=/workdir/test/scripts/dcn_parquet_distributed_4node_2gpu.json"


srun --ntasks=2 --container-image="${CONT}" --container-mounts="${MOUNTS}" --network sharp bash -cx " \
    export NCCL_IB_HCA=\"=mlx5_1\" && \
    cd /dataset/criteo_kaggle/dcn_parquet && \
    python3 /workdir/test/pybind_test/multi_node_test.py --json-file=/workdir/test/scripts/dcn_parquet_localized_2node_4gpu.json"
