#!/bin/bash

srun --ntasks="${SLURM_JOB_NUM_NODES}" --container-image="${CONT}" --container-mounts="${MOUNTS}" bash -cx " \
      cd /dataset/criteo_kaggle/dcn; \
      python3 /workdir/test/pybind_test/single_node_test.py --json-file=/workdir/test/scripts/dcn_8gpu.json && \
      python3 /workdir/test/pybind_test/single_node_test.py --json-file=/workdir/test/scripts/dcn_localized_embedding_8gpu.json && \
      cd /dataset/criteo_kaggle/dcn_parquet && \
      python3 /workdir/test/pybind_test/single_node_test.py --json-file=/workdir/test/scripts/dcn_parquet_distributed_8gpu.json && \
      python3 /workdir/test/pybind_test/single_node_test.py --json-file=/workdir/test/scripts/dcn_parquet_localized_8gpu.json && \
      cd /dataset/criteo_kaggle/dcn_parquet_vec_column && \
      python3 /workdir/test/pybind_test/single_node_test.py --json-file=/workdir/test/scripts/dcn_parquet_distributed_8gpu.json && \
      python3 /workdir/test/pybind_test/single_node_test.py --json-file=/workdir/test/scripts/dcn_parquet_localized_8gpu.json"
